name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main  
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.APP_PUBLISH_PROFILE }}
  WEBAPP_NAME: "testing-from-github"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Create .env file
        run: |
            echo "AUTH0_SECRET=${AUTH0_SECRET}" >> .env
            echo "APP_BASE_URL=${APP_BASE_URL}" >> .env
            echo "AUTH0_DOMAIN=${AUTH0_DOMAIN}" >> .env
            echo "AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}" >> .env
            echo "AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}" >> .env
            echo "AUTH0_AUDIENCE=${AUTH0_AUDIENCE}" >> .env
            echo "PROPIO_BACKEND_URL=${PROPIO_BACKEND_URL}" >> .env
            echo "FOO=${FOO}" >> .env
            
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: ./build/standalone